id: AB43B8E1E
title: CVIII_ยง24
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 22:05:51.337281
  last_modified_at: 2022-03-01 22:05:51.337284
