id: AB43B8E1E
title: CII_ยง10
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 22:05:51.145570
  last_modified_at: 2022-03-01 22:05:51.145573
