id: AB43B8E1E
title: CVI_ยง15
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 22:05:51.405227
  last_modified_at: 2022-03-01 22:05:51.405231
