id: AB43B8E1E
title: CIV_ยง20
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 22:05:51.203368
  last_modified_at: 2022-03-01 22:05:51.203370
