id: AB43B8E1E
title: CVII_ยง5
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 22:05:51.380055
  last_modified_at: 2022-03-01 22:05:51.380059
