id: AB43B8E1E
title: CIII_ยง13
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 22:05:50.980476
  last_modified_at: 2022-03-01 22:05:50.980479
