id: AB43B8E1E
title: CI_ยง7
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 22:05:51.301389
  last_modified_at: 2022-03-01 22:05:51.301392
